apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/creatorId: cwolsen
  name: sowing-me-admin-api
  namespace: ws-sandbox
  selfLink: /apis/networking.k8s.io/v1/namespaces/ws-sandbox/ingresses/sowing-me-admin-api
spec:
  rules:
  - host: sowing-me-admin-api.sb.vsmedia.net
    http:
      paths:
      - backend:
          service:
            name: sowing-me-admin-api
            port:
              number: 80
        path: /
        pathType: Prefix
