FROM node:20

WORKDIR /app

COPY app/SowingMeJs/package*.json ./
RUN npm install

COPY app/SowingMeJs/. .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "preview", "--", "--port", "3000", "--host", "0.0.0.0"]