{{- if and (not .Values.existingSecret) (or .Values.webhookSecret .Values.projectTokens) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ubix-ops.fullname" . }}
  labels:
    {{- include "ubix-ops.labels" . | nindent 4 }}
type: Opaque
stringData:
  GITLAB_WEBHOOK_SECRET: {{ .Values.webhookSecret | quote }}
  GITLAB_PROJECT_TOKENS: {{ .Values.projectTokens | quote }}
{{- end }}
