apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/creatorId: cwolsen
  name: affiliate-api
  namespace: webservices-sandbox
  selfLink: /apis/networking.k8s.io/v1/namespaces/webservices-sandbox/ingresses/affiliate-api
spec:
  rules:
  - host: affiliate-api.sb.vsmedia.net
    http:
      paths:
      - backend:
          service:
            name: affiliate-api
            port:
              number: 80
        path: /
        pathType: Prefix
