apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/creatorId: cwolsen
  labels:
    cattle.io/creator: norman
  name: affiliate-api
  namespace: webservices-staging
  selfLink: /apis/networking.k8s.io/v1/namespaces/webservices-staging/ingresses/affiliate-api
spec:
  rules:
  - host: affiliate-api.staging.vsmedia.net
    http:
      paths:
      - backend:
          service:
            name: affiliate-api
            port:
              number: 8080
        path: /
        pathType: Prefix
