apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    field.cattle.io/creatorId: cwolsen
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-ws-staging-sowing-me-api
  name: sowing-me-api
  namespace: ws-staging
  selfLink: /apis/apps/v1/namespaces/ws-staging/deployments/sowing-me-api
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-ws-staging-sowing-me-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":8080,"dnsName":"sowing-me-api","hostPort":0,"kind":"ClusterIP","name":"8080tcp02","protocol":"TCP","sourcePort":0}]]'
        date: "{{DATE_STAMP}}"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-ws-staging-sowing-me-api
    spec:
      containers:
      - env:
        - name: IN_DEV
          value: "0"
        - name: ENV
          value: "STAGING"
        - name: APP_NAME
          value: "SowingMeApi"
        image: gitlab.brainchurts.com:5050/ubixsys/ubixcore:staging
        imagePullPolicy: Always
        name: sowing-me-api
        ports:
        - containerPort: 8080
          name: 8080tcp02
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /logs
          name: logs
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /logs
          type: DirectoryOrCreate
        name: logs
